
export const AuthActionType = {
    LOGIN:      "LOGIN",
    LOGOUT:     "LOGOUT",
    ME:         "ME",
    REFRESHED:  "REFRESHED",
}

export const InviteActionType = {
    SET_PENDING_INVITATIONS: "SET_PENDING_INVITATIONS",
    SET_INVITATIONS: "SET_INVITATIONS",
    SET_ACCEPTED_INVITATIONS: "SET_ACCEPTED_INVITATIONS",
    SEND_INVITE: "SEND_INVITE",
}
